### ISSUE TITLE
Backups failing (version 1.0.11)

### ISSUE THREAD

**Issue by sm8ps** [Lernstick/glados#118]
With version 1.0.11 it seems that all backups are failing. Right upon starting an exam, there is a Zenity message on the user's desktop stating that there has been no backup since 22 mio. minutes which is absurd. When checking the exams from Glados there seems to be a lot of problems with rdiff-backup (cf. screenshot below).
![Bildschirmaufnahme vom 2021-11-01 08:23:12](https://user-images.githubusercontent.com/3989424/139636631-90663bb4-5b41-4b1b-acfb-5f4905164d2c.png)
I must add that the client hardware, including network connection via WLAN, is at the very lowest limits so I cannot exclude that as a possible cause.

**Comment by sm8ps** [comment]
As an encore the handing in process of the exams blocks at the last backup. I just had 100% out of 25 exams failing at that point and all the tickets remaining in the attributed state.

**Comment by chaoos** [comment]
Can you provide the output of one of these log files mentioned in the issues of the screenshot you posted? You also find them in the ticket view (under backups). There the full output of rdiffback is visible.
Also, do you use a Debian 11 Lernstick? If yes, Debian 11 Lernsticks are not supported by Glados 1.0.11 (comes in the next release).

**Comment by sm8ps** [comment]
Thanks for your immediate response! The log file all lock like the following:
```
Could not create directory '/var/www/.ssh'.
Warning: Permanently added '172.23.14.4' (ECDSA) to the list of known hosts.
Fatal Error: Source directory /overlay/home/user/Screenshots does not exist
Using rdiff-backup version 1.2.8
Executing ssh -i /var/lib/glados/.ssh/rsa -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no -C root@172.23.14.4 rdiff-backup-server
Fatal Error: Lost connection to the remote system
```

The Lernsticks show "10.8" under '/etc/debian_version'.

**Comment by sm8ps** [comment]
This is what happens when trying to view a ticket, either running (during a new exam) or assigned (the left-over tickets from the previous exam):
```
Fehler (#8)
Es ist ein interner Serverfehler aufgetreten.
Der Fehler oben passierte, während der Webserver Ihre Anfrage verarbeitete.
Bitte kontaktieren Sie uns, falls Sie denken, dass das ein Server Fehler ist. Vielen Dank.
```

**Comment by chaoos** [comment]
The problem is in this line:

    Fatal Error: Source directory /overlay/home/user/Screenshots does not exist

The Screenshots directory does not exist on the client, thus rdiff-backup fails to backup this directory. In the exam configuration, what is the value of the "Remote Backup Path" field? You should find that in the exam view or update form.

**Comment by sm8ps** [comment]
The remote backup path is indeed set to "/home/user/Screenshots" in accordance to the [Glados HowTo](http://172.10.0.26/glados/index.php/howto/remote-backup-path.md). I did so because the mentioned backup errors had been frequent before -- though (maybe?) not 100 percent -- when it was set to "/home/user/" and I suspected that this might overload the backup process.

I have set it back for an upcoming exam on Wednesday and shall report back afterwards.

**Comment by chaoos** [comment]
I recommend to leave it to `/home/user`, because - as it seems - if  the directory `/home/user/Screenshots` does not exist on the target, the backup fails as long as there is no such directory. Also the Screenshots directory recently changed to `/home/user/.Screenshots` (probably that was the main cause here). However, I'm quite certain that the non-existence of that directory in the backups also causes the internal server error you mentioned previously. I'll check that and take it in the todo to fix.

Thanks for the report.
Roman

**Comment by sm8ps** [comment]
PS: you may also want to adapt the HowTo section "Remote backup path".

**Comment by sm8ps** [comment]
The issue did not reproduce itself in the last two exams. Thanks for your support!
